### ISSUE TITLE
Releasing

### ISSUE THREAD

**Issue by amis92** [BSData/f28#1]
Hi @jonnyhjorter.

I noticed the recent releases you did and wanted to offer some guidance on the BSData release structure. You created git tags and pre-releases, but not releases, which is not the correct approach.

https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide#releasing has our standards listed. In short we try to keep to a vMajor.Minor.Bugfix structure for the tags, this allows us to try and have a similar structure throughout the various systems. Also there is a bot that we've added to help with this. All you have to do create an issue comment that starts with `/release`:

> /release
> \<Title of Release>
> \<Details of Release (If you want)>

Our bot will automatically push a release with the proper version incrementation as well as a changelog right in the release details.

Details about that release command can be found here: https://github.com/BSData/chatops#release-command

Please feel free to join us here https://discord.gg/KqPVhds for any assistance or questions.

---
From https://github.com/BSData/f28/commit/dd0901f044977d9acc26f1a66fc6e3651660efb0#commitcomment-42923859

**Comment by jonnyhjorter** [comment]
Hi @amis92 

Thanks for the tip. I have tried to follow the release guide you pointed to and have now released v1.0.0 as I have added all factions from the rulebook. However, the guide don't say anything about using pre-releses and as you pointed out, they should not be used. Maybe update the guide with that info? 

Thanks again for the tip and please reach out again if I do something odd or wrong.
